# License: BSD-3-Clause license
# Author: Piotr Marendowski
# Purpose: Makefile for project 1
# Dependencies: stack.c, stack.h
# Modification date (DD/MM/YYYY): 20.12.2022

project: stack.o
	gcc stack.o -o project

stack.o: stack.c stack.h
	gcc -c stack.c